// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"database/sql"

	"github.com/google/uuid"
)

type Item struct {
	ID        uuid.UUID
	Name      string
	Timestamp sql.NullTime
}
