version: '3.9'

services:
  shopping-list-postgres:
    image: postgres:latest
    ports:
      - "15432:5432"
    volumes:
      - /var/lib/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=shopping-list